[package]
name = "cgp_rs"
version = "0.1.1"
authors = ["Anthony Meehan <acm49@students.waikato.ac.nz>",
           "thegoldencanary <thegoldencanary8@gmail.com>"]

[dependencies]
rand = "0.3.15"
csv = "0.15.0"